
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.19"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.9"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.98"
criteria = "safe-to-deploy"

[[exemptions.arraydeque]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.assert_cmd]]
version = "2.0.17"
criteria = "safe-to-run"

[[exemptions.assert_fs]]
version = "1.1.3"
criteria = "safe-to-run"

[[exemptions.async-trait]]
version = "0.1.88"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.75"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bstr]]
version = "1.12.0"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.2.27"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.41"
criteria = "safe-to-deploy"

[[exemptions.chrono-tz]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.chrono-tz-build]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.40"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.40"
criteria = "safe-to-deploy"

[[exemptions.clap_complete]]
version = "4.5.54"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.40"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.clap_mangen]]
version = "0.2.27"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.config]]
version = "0.15.11"
criteria = "safe-to-deploy"

[[exemptions.const-random]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.const-random-macro]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.difflib]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.dlv-list]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-run"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.13"
criteria = "safe-to-run"

[[exemptions.exitcode]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.float-cmp]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.foldhash]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.globset]]
version = "0.4.16"
criteria = "safe-to-run"

[[exemptions.globwalk]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.4"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.human-date-parser]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.ignore]]
version = "0.4.23"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.json5]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.174"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.9.4"
criteria = "safe-to-run"

[[exemptions.lock_api]]
version = "0.4.13"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.normalize-line-endings]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.ordered-multimap]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.4"
criteria = "safe-to-run"

[[exemptions.parking_lot_core]]
version = "0.9.11"
criteria = "safe-to-run"

[[exemptions.parse-zoneinfo]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.pathdiff]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.pest_consume]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pest_consume_macros]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.phf]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_codegen]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_generator]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_shared]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.predicates]]
version = "3.1.3"
criteria = "safe-to-run"

[[exemptions.predicates-core]]
version = "1.0.9"
criteria = "safe-to-run"

[[exemptions.predicates-tree]]
version = "1.0.12"
criteria = "safe-to-run"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.40"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-run"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.10.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.12.1"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.5.13"
criteria = "safe-to-run"

[[exemptions.redox_users]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.roff]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ron]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.rust-ini]]
version = "0.21.1"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.7"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.21"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.scc]]
version = "2.3.4"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.sdd]]
version = "3.0.8"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.219"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.219"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.140"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.9"
criteria = "safe-to-deploy"

[[exemptions.serial_test]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.serial_test_derive]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.sha2]]
version = "0.10.9"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.10"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-run"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.104"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.20.0"
criteria = "safe-to-run"

[[exemptions.termtree]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tiny-keccak]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "0.8.23"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.11"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.22.27"
criteria = "safe-to-deploy"

[[exemptions.toml_write]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.trim-in-place]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.14.2+wasi-0.2.4"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-run"

[[exemptions.windows-core]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.0"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.1"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust2]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"
