name: Smoke tests

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:

jobs:
  smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build & install td (path)
        run: cargo install --path . --locked --force

      - name: Smoke 1 – literal date
        run: |
          out=$(td "2025-06-25 13:00" -f "%Y-%m-%dT%H:%M")
          [[ "$out" == "2025-06-25T13:00" ]]

      - name: Smoke 2 – relative date
        run: |
          out=$(td "in 1 hour" -f "%s" --now "2025-01-01T00:00:00Z")
          [[ "$out" == "1735693200" ]]

      - name: Smoke 3 – preset resolution
        run: |
          cfg_root="$PWD/_tardis_cfg"
          mkdir -p "$cfg_root/tardis"
          export XDG_CONFIG_HOME="$cfg_root"
          cat > "$cfg_root/tardis/config.toml" <<'EOF'
          format = "%Y"
          timezone = "UTC"

          [formats]
          br = "%d/%m/%Y"
          EOF
          [[ "$(td "2025-12-31" -f br)" == "31/12/2025" ]]
